# Merge hai bộ nhãn mental-state và setiment qua cột question

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('mental_health_eng_viet.csv')
data.shape

(970421, 2)

In [5]:
data.head()

,question,answer
0,Tôi nghĩ nó có thể là sự kết hợp của nhiều thứ...,Cảm nhận được sức nặng của những kỳ vọng bên n...
1,"I've been trying to, but it's been challenging...",Letting go can be incredibly difficult. It's o...
2,Không phải lúc này. Sự hướng dẫn của bạn ngày ...,Tôi rất vui vì có thể giúp được anh. Hãy nhớ r...
3,Gần đây tôi cảm thấy thực sự buồn. Thật khó để...,", tôi có thể cảm nhận được nỗi buồn của bạn. L..."
4,"Vâng, tôn giáo là một tôn giáo lớn. Tôi đã chọ...",Điều đó hẳn là vô cùng khó khăn. Việc họ không...

In [4]:
df_mental = pd.read_csv('/home/aero/DoAnTotNghiep/Notebook/pseudo_mental_state.csv')
df_sent = pd.read_csv('setimet_labeled_full.csv')

In [ ]:
df_mental.shape

(831077, 4)

In [7]:
df_mental = df_mental.rename(columns={'statement': 'question'})

In [9]:
df_merged.shape

(2337534, 5)

In [4]:
df_mental.head()

,statement,predicted_label_id,predicted_status,confidence
0,Tôi nghĩ nó có thể là sự kết hợp của nhiều thứ...,5,Stress,0.772602
1,"I've been trying to, but it's been challenging...",6,Suicidal,0.995539
2,Không phải lúc này. Sự hướng dẫn của bạn ngày ...,1,Bipolar,0.416023
3,Gần đây tôi cảm thấy thực sự buồn. Thật khó để...,2,Depression,0.999423
4,"Vâng, tôn giáo là một tôn giáo lớn. Tôi đã chọ...",3,Normal,0.911468

In [5]:
df_mental = pd.read_csv('/home/aero/DoAnTotNghiep/Notebook/pseudo_mental_state_softlabel.csv')

In [7]:
df_mental.shape
df_mental.head()

,statement,predicted_label_id,predicted_status,confidence,probs
0,Tôi nghĩ nó có thể là sự kết hợp của nhiều thứ...,1,Bipolar,0.203070,"[0.14711619913578033, 0.2030700147151947, 0.15..."
1,"I've been trying to, but it's been challenging...",1,Bipolar,0.207632,"[0.13157472014427185, 0.2076323926448822, 0.13..."
2,Không phải lúc này. Sự hướng dẫn của bạn ngày ...,6,Suicidal,0.191458,"[0.1483916938304901, 0.13417313992977142, 0.16..."
3,Gần đây tôi cảm thấy thực sự buồn. Thật khó để...,5,Stress,0.202646,"[0.09355734288692474, 0.1837037056684494, 0.12..."
4,"Vâng, tôn giáo là một tôn giáo lớn. Tôi đã chọ...",3,Normal,0.164478,"[0.13914868235588074, 0.11889137327671051, 0.1..."

In [10]:
df_mental = pd.read_csv('/home/aero/DoAnTotNghiep/Notebook/mental_state_dataset.csv') # Dự liệu gốc + dữ liệu gen từ gemini
df_mental.shape

(390475, 2)

In [9]:
df_mental.head()

                                           statement    status
0  Dạo này tôi không hiểu sao cứ bị những cơn hoả...  Suicidal
1  Tôi đang ở đây, gõ những dòng này, khóc nức nở...  Suicidal
2  Những ý nghĩ tự tử chỉ là thoáng qua thôi. Tôi...  Suicidal
3  Tôi biết những suy nghĩ tiêu cực về việc tự tử...  Suicidal
4  Hãy nhớ rằng, ý nghĩ tự sát chỉ là nhất thời. ...  Suicidal

In [11]:
df_mental = pd.read_csv('augmented_labeled_full.csv')
df_mental.shape

(401259, 2)

In [12]:
df_mental.head()

                                           statement     label
0  Dạo này tôi không hiểu sao cứ bị những cơn hoả...  Suicidal
1  Tôi đang ở đây, gõ những dòng này, khóc nức nở...  Suicidal
2  Những ý nghĩ tự tử chỉ là thoáng qua thôi. Tôi...  Suicidal
3  Tôi biết những suy nghĩ tiêu cực về việc tự tử...  Suicidal
4  Hãy nhớ rằng, ý nghĩ tự sát chỉ là nhất thời. ...  Suicidal

In [13]:
df_mental = pd.read_csv("augmented_labeled_full_final.csv")
df_mental.shape

(219909, 2)

In [14]:
df_mental.head()

                                           statement   status
0  Dưới đây là một số cách diễn đạt khác nhau cho...  Bipolar
1  Lo lắng của tôi ngày càng trầm trọng, thuốc me...  Bipolar
2  Tôi đang trong cơn tuyệt vọng vì thuốc chống l...  Bipolar
3  Cơn lo âu hành hạ tôi dữ dội, thuốc  không còn...  Bipolar
4  Tôi thực sự tuyệt vọng, thuốc lo âu liều cao n...  Bipolar

In [16]:
df_mental = pd.read_csv('augmented_labeled_full copy.csv')
df_mental.shape

(242861, 2)

In [17]:
df_mental.head()

                                           statement    label
0  Dưới đây là một số cách diễn đạt khác nhau cho...  Bipolar
1  Lo lắng của tôi ngày càng trầm trọng, thuốc me...  Bipolar
2  Tôi đang trong cơn tuyệt vọng vì thuốc chống l...  Bipolar
3  Cơn lo âu hành hạ tôi dữ dội, thuốc  không còn...  Bipolar
4  Tôi thực sự tuyệt vọng, thuốc lo âu liều cao n...  Bipolar